import { Assumptions, Zone, ElectricalLoad, ControlRule, WhatsAppAlert } from '../types';

export const DEFAULT_ASSUMPTIONS: Assumptions = {
  numBeds: 50,
  gridTariffPerKwh: 9.5, // Indian commercial hospital tariff (₹/kWh)
  dieselGenTariffPerKwh: 28.0, // DG fuel + maintenance cost (₹/kWh)
  kitCostInr: 285000, // Total retrofit kit + installation (₹2.85 Lakhs)
  annualMaintenanceInr: 18000, // Annual cloud telemetry + sensor check
  solarCapacityKwp: 30, // 30 kWp rooftop solar PV
  batteryCapacityKwh: 45, // 45 kWh LFP battery buffer
  batteryMaxDischargeKw: 15,
  peakTariffMultiplier: 1.35, // Time-of-day peak surcharge
  peakHourStart: 18, // 6 PM
  peakHourEnd: 22, // 10 PM
  outdoorTempMinSummer: 27,
  outdoorTempMaxSummer: 39.5,
  outdoorTempMinHeatwave: 31,
  outdoorTempMaxHeatwave: 44.5,
  fanCoolingEquivalenceC: 1.0, // 1°C thermal offset when ceiling fan runs
  corridorDimmingMinLux: 80, // NABH standard minimum corridor lux for patient safety
};

export const INITIAL_ZONES: Zone[] = [
  {
    id: 'zone-ot',
    name: 'Operating Theatre Complex (Major & Minor)',
    tag: 'RED',
    areaSqM: 110,
    baseTemp: 20.5,
    targetTemp: 20.5,
    safeTempBand: [19.5, 21.5],
    occupancyMax: 8,
    svgCoords: { x: 30, y: 30, w: 220, h: 160 },
    loads: ['load-ot-ahu', 'load-ot-scrub', 'load-ot-light', 'load-ot-ups'],
    description: 'Ultra-clean sterile surgical suite with HEPA filtration and laminar air flow.',
    clinicalNote: 'CRITICAL CLINICAL ZONE: Uninterrupted positive pressure and strict temperature 20-21°C required. No energy curtailment permitted by NABH/MOHFW guidelines.',
  },
  {
    id: 'zone-icu',
    name: 'Intensive Care Unit (5 Beds)',
    tag: 'RED',
    areaSqM: 95,
    beds: 5,
    baseTemp: 21.5,
    targetTemp: 21.5,
    safeTempBand: [20.5, 22.5],
    occupancyMax: 10,
    svgCoords: { x: 270, y: 30, w: 210, h: 160 },
    loads: ['load-icu-hvac', 'load-icu-monitors', 'load-icu-suction'],
    description: 'High-dependency 5-bed unit with mechanical ventilators and continuous hemodynamics.',
    clinicalNote: 'CRITICAL CLINICAL ZONE: Vulnerable post-operative and septic patients. Strict continuous thermal comfort & uninterrupted medical gas systems.',
  },
  {
    id: 'zone-pharmacy',
    name: 'Pharmacy & Vaccine Cold Chain',
    tag: 'RED',
    areaSqM: 45,
    baseTemp: 4.2, // internal vaccine storage
    targetTemp: 4.0,
    safeTempBand: [2.0, 8.0],
    occupancyMax: 3,
    svgCoords: { x: 500, y: 30, w: 180, h: 160 },
    loads: ['load-pharmacy-fridge', 'load-pharmacy-light', 'load-pharmacy-ac'],
    description: 'WHO-prequalified vaccine refrigerators and refrigerated bio-pharmaceutical storage.',
    clinicalNote: 'VACCINE COLD CHAIN: Biological spoilage if temperatures exceed 8°C or drop below 2°C for >15 minutes. Hardware locked from any switching.',
  },
  {
    id: 'zone-ward-a',
    name: 'General Ward A (20 Beds - Male)',
    tag: 'YELLOW',
    areaSqM: 180,
    beds: 20,
    baseTemp: 24.5,
    targetTemp: 24.0,
    safeTempBand: [23.5, 26.5],
    occupancyMax: 28,
    svgCoords: { x: 30, y: 210, w: 270, h: 170 },
    loads: ['load-ward-a-ac1', 'load-ward-a-ac2', 'load-ward-a-fans', 'load-ward-a-lights'],
    description: 'Inpatient recovery ward with 20 recovery beds and attached nurse station.',
    clinicalNote: 'COMFORT ZONE: Controlled within clinician-approved safe temperature band (24.0°C - 26.0°C). Ceiling fans coordinated with AC setpoint.',
  },
  {
    id: 'zone-ward-b',
    name: 'General Ward B (15 Beds - Female & Pediatric)',
    tag: 'YELLOW',
    areaSqM: 150,
    beds: 15,
    baseTemp: 24.5,
    targetTemp: 24.0,
    safeTempBand: [23.5, 26.5],
    occupancyMax: 22,
    svgCoords: { x: 320, y: 210, w: 250, h: 170 },
    loads: ['load-ward-b-ac1', 'load-ward-b-ac2', 'load-ward-b-fans', 'load-ward-b-lights'],
    description: 'Pediatric and female post-surgical inpatient recovery ward with 15 beds.',
    clinicalNote: 'COMFORT ZONE: Safe thermal comfort band. Empty beds put in deep setback while occupied beds retain comfortable airflow.',
  },
  {
    id: 'zone-opd',
    name: 'OPD Reception & Waiting Hall (40 Seats)',
    tag: 'YELLOW',
    areaSqM: 130,
    baseTemp: 25.0,
    targetTemp: 24.5,
    safeTempBand: [24.0, 27.0],
    occupancyMax: 45,
    svgCoords: { x: 590, y: 210, w: 240, h: 170 },
    loads: ['load-opd-cassette-ac', 'load-opd-fans', 'load-opd-tv-lighting'],
    description: 'Outpatient registration, token queue display, and patient waiting area.',
    clinicalNote: 'DYNAMIC OCCUPANCY: High crowding during 09:30-13:00 and 16:30-19:30. Modulate cooling dynamically with queue token count.',
  },
  {
    id: 'zone-corridors',
    name: 'Central Corridors & Stretcher Ramps',
    tag: 'YELLOW',
    areaSqM: 120,
    baseTemp: 27.0,
    targetTemp: 27.0,
    safeTempBand: [22.0, 30.0],
    occupancyMax: 15,
    svgCoords: { x: 30, y: 400, w: 420, h: 120 },
    loads: ['load-corridor-light-gf', 'load-corridor-light-1f', 'load-ramp-exhaust'],
    description: 'Primary circulation spine, triage entry ramp, and nurse transit pathways.',
    clinicalNote: 'SAFETY-CRITICAL LIGHTING: Dims to 50% between 23:00-05:00 but guaranteed >80 lux for night emergency stretcher transfers.',
  },
  {
    id: 'zone-admin',
    name: 'Admin, Billing & Doctor Consultation',
    tag: 'YELLOW',
    areaSqM: 90,
    baseTemp: 24.5,
    targetTemp: 24.0,
    safeTempBand: [23.5, 27.0],
    occupancyMax: 12,
    svgCoords: { x: 470, y: 400, w: 180, h: 120 },
    loads: ['load-admin-split-ac', 'load-admin-workstations', 'load-admin-lighting'],
    description: 'Medical records, health insurance TPA desk, and medical director office.',
    clinicalNote: 'OFFICE ZONE: Auto-standby after 19:30 when administrative staff depart.',
  },
  {
    id: 'zone-utility',
    name: 'Utility & Services Yard (Pump, Laundry, Sterilisation)',
    tag: 'GREEN',
    areaSqM: 140,
    baseTemp: 31.0,
    targetTemp: 31.0,
    safeTempBand: [18.0, 38.0],
    occupancyMax: 6,
    svgCoords: { x: 670, y: 400, w: 210, h: 120 },
    loads: ['load-pump-water', 'load-laundry-wash', 'load-autoclave-preheat', 'load-ro-plant'],
    description: 'Hospital infrastructure hub: raw water pump, linen washer, autoclave boiler, RO water plant.',
    clinicalNote: 'FLEXIBLE SHIFTING LOADS: Zero patient touchpoint. Shifted entirely to match rooftop solar generation and off-peak tariff periods.',
  },
];

export const INITIAL_LOADS: ElectricalLoad[] = [
  // RED LOADS (Clinical Lockout)
  {
    id: 'load-ot-ahu',
    name: 'OT Laminar Air Handling Unit (AHU) & HEPA',
    zoneId: 'zone-ot',
    zoneName: 'Operating Theatre',
    tag: 'RED',
    originalTag: 'RED',
    ratedKw: 8.5,
    category: 'HVAC',
    isControllable: false,
    lockoutReason: 'NABH / Clinical Risk Level 1: Surgical infection risk if air changes or pressure drop.',
    ctSensorId: 'CT-OT-01',
    bypassRelay: 'NONE',
    baselineSchedule: 'Continuous 24x7 100% duty',
    triageStrategy: 'Monitor-only; real-time anomaly detection on filter resistance',
  },
  {
    id: 'load-ot-scrub',
    name: 'OT Medical Gas & Surgical Vacuum Scavenger',
    zoneId: 'zone-ot',
    zoneName: 'Operating Theatre',
    tag: 'RED',
    originalTag: 'RED',
    ratedKw: 3.2,
    category: 'CRITICAL_MEDICAL',
    isControllable: false,
    lockoutReason: 'Life support / Anesthesia gas scavenging system. Zero interruption permitted.',
    ctSensorId: 'CT-OT-02',
    bypassRelay: 'NONE',
    baselineSchedule: 'Continuous 24x7',
    triageStrategy: 'Monitor-only; zero control contacts physically wired',
  },
  {
    id: 'load-ot-light',
    name: 'Surgical Shadowless LED Luminaires',
    zoneId: 'zone-ot',
    zoneName: 'Operating Theatre',
    tag: 'RED',
    originalTag: 'RED',
    ratedKw: 1.2,
    category: 'LIGHTING',
    isControllable: false,
    lockoutReason: 'Surgical field illumination. Must never be dimmed or switched.',
    ctSensorId: 'CT-OT-03',
    bypassRelay: 'NONE',
    baselineSchedule: 'Operational during surgeries',
    triageStrategy: 'Monitor-only via CT sensor',
  },
  {
    id: 'load-ot-ups',
    name: 'OT Isolated Medical Isolated Power Supply (IPS)',
    zoneId: 'zone-ot',
    zoneName: 'Operating Theatre',
    tag: 'RED',
    originalTag: 'RED',
    ratedKw: 4.0,
    category: 'CRITICAL_MEDICAL',
    isControllable: false,
    lockoutReason: 'Electrosurgical diathermy, anesthesia workstation and heart-lung monitors.',
    ctSensorId: 'CT-OT-04',
    bypassRelay: 'NONE',
    baselineSchedule: 'Continuous standby/active',
    triageStrategy: 'Monitor-only; leakage current tracking',
  },
  {
    id: 'load-icu-hvac',
    name: 'ICU Dedicated Precision Air Conditioning',
    zoneId: 'zone-icu',
    zoneName: 'ICU',
    tag: 'RED',
    originalTag: 'RED',
    ratedKw: 7.0,
    category: 'HVAC',
    isControllable: false,
    lockoutReason: 'Patient thermoregulation & microbial control. Controlled strictly by clinical nursing staff.',
    ctSensorId: 'CT-ICU-01',
    bypassRelay: 'NONE',
    baselineSchedule: 'Continuous 24x7 at 21°C',
    triageStrategy: 'Monitor-only; compressor health verification',
  },
  {
    id: 'load-icu-monitors',
    name: 'ICU Ventilators & Multiparameter Monitors (x5)',
    zoneId: 'zone-icu',
    zoneName: 'ICU',
    tag: 'RED',
    originalTag: 'RED',
    ratedKw: 2.8,
    category: 'CRITICAL_MEDICAL',
    isControllable: false,
    lockoutReason: 'Direct patient life-support equipment. Absolutely no automated switching.',
    ctSensorId: 'CT-ICU-02',
    bypassRelay: 'NONE',
    baselineSchedule: 'Continuous 24x7',
    triageStrategy: 'Monitor-only via CT sensor with redundant power feed',
  },
  {
    id: 'load-icu-suction',
    name: 'Central Medical Suction & Oxygen Plant Booster',
    zoneId: 'zone-icu',
    zoneName: 'ICU',
    tag: 'RED',
    originalTag: 'RED',
    ratedKw: 2.5,
    category: 'CRITICAL_MEDICAL',
    isControllable: false,
    lockoutReason: 'Airway clearance and respiratory support for critical care.',
    ctSensorId: 'CT-ICU-03',
    bypassRelay: 'NONE',
    baselineSchedule: 'Demand-based automated pneumatic cycle',
    triageStrategy: 'Monitor-only; runtime and pressure degradation alerts',
  },
  {
    id: 'load-pharmacy-fridge',
    name: 'Vaccine & Biological Storage ILR Refrigerator',
    zoneId: 'zone-pharmacy',
    zoneName: 'Pharmacy & Cold Chain',
    tag: 'RED',
    originalTag: 'RED',
    ratedKw: 1.1,
    category: 'REFRIGERATION',
    isControllable: false,
    lockoutReason: 'Critical Vaccine Cold Chain (2°C - 8°C). Any power cutoff risks lakh of rupees in lost vaccines.',
    ctSensorId: 'CT-PHARM-01',
    bypassRelay: 'NONE',
    baselineSchedule: 'Continuous 24x7 with internal thermostat',
    triageStrategy: 'Monitor-only; high-resolution dual thermistor alerts if >6.5°C',
  },
  {
    id: 'load-pharmacy-light',
    name: 'Emergency Pharmacy Dispensing Counter Light',
    zoneId: 'zone-pharmacy',
    zoneName: 'Pharmacy & Cold Chain',
    tag: 'RED',
    originalTag: 'RED',
    ratedKw: 0.4,
    category: 'LIGHTING',
    isControllable: false,
    lockoutReason: 'Accuracy of drug dispensing at night to prevent dosage errors.',
    ctSensorId: 'CT-PHARM-02',
    bypassRelay: 'NONE',
    baselineSchedule: 'Continuous 24x7',
    triageStrategy: 'Monitor-only',
  },

  // YELLOW LOADS (Safe Band Controlled)
  {
    id: 'load-ward-a-ac1',
    name: 'Ward A North Inverter Split AC (3.0 TR)',
    zoneId: 'zone-ward-a',
    zoneName: 'General Ward A',
    tag: 'YELLOW',
    originalTag: 'YELLOW',
    ratedKw: 3.6,
    category: 'HVAC',
    isControllable: true,
    ctSensorId: 'CT-WDA-01',
    bypassRelay: 'NC_CONTACTOR',
    baselineSchedule: 'Fixed 22°C setpoint 24 hours',
    triageStrategy: 'Fan-first +1°C setpoint nudge (24.5°C) & empty-bed setback',
  },
  {
    id: 'load-ward-a-ac2',
    name: 'Ward A South Inverter Split AC (3.0 TR)',
    zoneId: 'zone-ward-a',
    zoneName: 'General Ward A',
    tag: 'YELLOW',
    originalTag: 'YELLOW',
    ratedKw: 3.6,
    category: 'HVAC',
    isControllable: true,
    ctSensorId: 'CT-WDA-02',
    bypassRelay: 'NC_CONTACTOR',
    baselineSchedule: 'Fixed 22°C setpoint 24 hours',
    triageStrategy: 'Fan-first +1°C setpoint nudge (24.5°C) & empty-bed setback',
  },
  {
    id: 'load-ward-a-fans',
    name: 'Ward A BLDC Ceiling Fans (x10)',
    zoneId: 'zone-ward-a',
    zoneName: 'General Ward A',
    tag: 'YELLOW',
    originalTag: 'YELLOW',
    ratedKw: 0.35,
    category: 'HVAC',
    isControllable: true,
    ctSensorId: 'CT-WDA-03',
    bypassRelay: 'NC_CONTACTOR',
    baselineSchedule: 'Manually switched',
    triageStrategy: 'Speed optimized to provide 0.8 m/s skin velocity, enabling AC offset',
  },
  {
    id: 'load-ward-a-lights',
    name: 'Ward A General LED Ceiling Panels',
    zoneId: 'zone-ward-a',
    zoneName: 'General Ward A',
    tag: 'YELLOW',
    originalTag: 'YELLOW',
    ratedKw: 0.8,
    category: 'LIGHTING',
    isControllable: true,
    ctSensorId: 'CT-WDA-04',
    bypassRelay: 'NC_CONTACTOR',
    baselineSchedule: '100% full brightness 06:00 to 23:00',
    triageStrategy: 'Dimmed to 30% night mode (warm ambient) 22:00 to 05:30',
  },
  {
    id: 'load-ward-b-ac1',
    name: 'Ward B Split AC 1 (2.5 TR)',
    zoneId: 'zone-ward-b',
    zoneName: 'General Ward B',
    tag: 'YELLOW',
    originalTag: 'YELLOW',
    ratedKw: 3.0,
    category: 'HVAC',
    isControllable: true,
    ctSensorId: 'CT-WDB-01',
    bypassRelay: 'NC_CONTACTOR',
    baselineSchedule: 'Fixed 22°C setpoint 24 hours',
    triageStrategy: 'Setback to 25.0°C during low occupancy hours',
  },
  {
    id: 'load-ward-b-ac2',
    name: 'Ward B Split AC 2 (2.5 TR)',
    zoneId: 'zone-ward-b',
    zoneName: 'General Ward B',
    tag: 'YELLOW',
    originalTag: 'YELLOW',
    ratedKw: 3.0,
    category: 'HVAC',
    isControllable: true,
    ctSensorId: 'CT-WDB-02',
    bypassRelay: 'NC_CONTACTOR',
    baselineSchedule: 'Fixed 22°C setpoint 24 hours',
    triageStrategy: 'Setback to 25.0°C during low occupancy hours',
  },
  {
    id: 'load-ward-b-fans',
    name: 'Ward B BLDC Ceiling Fans (x8)',
    zoneId: 'zone-ward-b',
    zoneName: 'General Ward B',
    tag: 'YELLOW',
    originalTag: 'YELLOW',
    ratedKw: 0.28,
    category: 'HVAC',
    isControllable: true,
    ctSensorId: 'CT-WDB-03',
    bypassRelay: 'NC_CONTACTOR',
    baselineSchedule: 'Manual switches',
    triageStrategy: 'Fan-first cooling interlock with AC units',
  },
  {
    id: 'load-ward-b-lights',
    name: 'Ward B General LED Panels',
    zoneId: 'zone-ward-b',
    zoneName: 'General Ward B',
    tag: 'YELLOW',
    originalTag: 'YELLOW',
    ratedKw: 0.6,
    category: 'LIGHTING',
    isControllable: true,
    ctSensorId: 'CT-WDB-04',
    bypassRelay: 'NC_CONTACTOR',
    baselineSchedule: 'Full brightness',
    triageStrategy: 'Night dimming scheduled automatically',
  },
  {
    id: 'load-opd-cassette-ac',
    name: 'OPD Reception Ceiling Cassette AC (4.0 TR)',
    zoneId: 'zone-opd',
    zoneName: 'OPD Waiting Hall',
    tag: 'YELLOW',
    originalTag: 'YELLOW',
    ratedKw: 4.8,
    category: 'HVAC',
    isControllable: true,
    ctSensorId: 'CT-OPD-01',
    bypassRelay: 'NC_CONTACTOR',
    baselineSchedule: 'Turned on at 08:00, left running till 21:00 at 22°C',
    triageStrategy: 'Token-linked modulation: 23.5°C during rush hours, 26.5°C during afternoon lull',
  },
  {
    id: 'load-opd-fans',
    name: 'OPD Waiting Heavy Duty Fans (x6)',
    zoneId: 'zone-opd',
    zoneName: 'OPD Waiting Hall',
    tag: 'YELLOW',
    originalTag: 'YELLOW',
    ratedKw: 0.45,
    category: 'HVAC',
    isControllable: true,
    ctSensorId: 'CT-OPD-02',
    bypassRelay: 'NC_CONTACTOR',
    baselineSchedule: 'Continuous morning till night',
    triageStrategy: 'Automated speed modulation based on queue crowd sensors',
  },
  {
    id: 'load-opd-tv-lighting',
    name: 'OPD Displays & Waiting Lighting',
    zoneId: 'zone-opd',
    zoneName: 'OPD Waiting Hall',
    tag: 'YELLOW',
    originalTag: 'YELLOW',
    ratedKw: 0.7,
    category: 'LIGHTING',
    isControllable: true,
    ctSensorId: 'CT-OPD-03',
    bypassRelay: 'NC_CONTACTOR',
    baselineSchedule: 'Manual switches',
    triageStrategy: 'Auto shutoff after 19:30 OPD closing',
  },
  {
    id: 'load-corridor-light-gf',
    name: 'Ground Floor Corridor LED Batten Array',
    zoneId: 'zone-corridors',
    zoneName: 'Central Corridors',
    tag: 'YELLOW',
    originalTag: 'YELLOW',
    ratedKw: 1.4,
    category: 'LIGHTING',
    isControllable: true,
    ctSensorId: 'CT-COR-01',
    bypassRelay: 'NC_CONTACTOR',
    baselineSchedule: '100% full power 24x7 365 days',
    triageStrategy: 'Night dimming to 45% (guaranteed >85 lux) between 23:00 - 05:00',
  },
  {
    id: 'load-corridor-light-1f',
    name: 'First Floor Stretcher Corridor Lighting',
    zoneId: 'zone-corridors',
    zoneName: 'Central Corridors',
    tag: 'YELLOW',
    originalTag: 'YELLOW',
    ratedKw: 1.2,
    category: 'LIGHTING',
    isControllable: true,
    ctSensorId: 'CT-COR-02',
    bypassRelay: 'NC_CONTACTOR',
    baselineSchedule: '100% full power 24x7',
    triageStrategy: 'Motion-activated step-up during late night stretcher transfers',
  },
  {
    id: 'load-admin-split-ac',
    name: 'Admin & Billing 2.0 TR Split AC',
    zoneId: 'zone-admin',
    zoneName: 'Admin & Billing',
    tag: 'YELLOW',
    originalTag: 'YELLOW',
    ratedKw: 2.4,
    category: 'HVAC',
    isControllable: true,
    ctSensorId: 'CT-ADM-01',
    bypassRelay: 'NC_CONTACTOR',
    baselineSchedule: 'Often left ON overnight by forgetful staff',
    triageStrategy: 'Hard occupancy cutoff at 20:00; alert WhatsApp if drawing power past 21:00',
  },

  // GREEN LOADS (Flexible Time Shiftable)
  {
    id: 'load-pump-water',
    name: 'Overhead Tank Raw & Borewell Pump (5 HP)',
    zoneId: 'zone-utility',
    zoneName: 'Utility Yard',
    tag: 'GREEN',
    originalTag: 'GREEN',
    ratedKw: 3.7,
    category: 'WATER',
    isControllable: true,
    ctSensorId: 'CT-UTL-01',
    bypassRelay: 'SMART_VFD',
    baselineSchedule: 'Turned on 06:30 and 18:30 (peak grid tariff window)',
    triageStrategy: 'Shifted to peak solar window (11:00 - 14:00) with ultrasound water level interlock',
  },
  {
    id: 'load-laundry-wash',
    name: 'Heavy Hospital Linen Washer & Hydro-Extractor',
    zoneId: 'zone-utility',
    zoneName: 'Utility Yard',
    tag: 'GREEN',
    originalTag: 'GREEN',
    ratedKw: 6.8,
    category: 'AUXILIARY',
    isControllable: true,
    ctSensorId: 'CT-UTL-02',
    bypassRelay: 'NC_CONTACTOR',
    baselineSchedule: 'Run in morning starting 08:30 during hospital peak surge',
    triageStrategy: 'Automated release signal when rooftop solar > 18 kW (11:30 - 14:30)',
  },
  {
    id: 'load-autoclave-preheat',
    name: 'CSSD Autoclave Boiler Pre-Heating Element',
    zoneId: 'zone-utility',
    zoneName: 'Utility Yard',
    tag: 'GREEN',
    originalTag: 'GREEN',
    ratedKw: 6.0,
    category: 'STERILIZATION',
    isControllable: true,
    ctSensorId: 'CT-UTL-03',
    bypassRelay: 'NC_CONTACTOR',
    baselineSchedule: 'Powered on arbitrary intervals before steam cycles',
    triageStrategy: 'Pre-heats water thermal buffer using mid-day surplus solar energy',
  },
  {
    id: 'load-ro-plant',
    name: 'Central RO Water Purification Plant (1000 LPH)',
    zoneId: 'zone-utility',
    zoneName: 'Utility Yard',
    tag: 'GREEN',
    originalTag: 'GREEN',
    ratedKw: 2.2,
    category: 'WATER',
    isControllable: true,
    ctSensorId: 'CT-UTL-04',
    bypassRelay: 'NC_CONTACTOR',
    baselineSchedule: 'Intermittent on/off cycles based on float switch',
    triageStrategy: 'Storage buffering: runs primary cycle between 10:00 and 15:00',
  },
];

export const INITIAL_RULES: ControlRule[] = [
  {
    id: 'rule-empty-bed',
    name: 'Empty-Bed Ward Standby Mode',
    category: 'HVAC',
    tagApplied: 'YELLOW',
    description: 'Narrows cooling focus in General Wards A & B. Sets unoccupied bed zones to 26°C while occupied cubicles maintain pleasant fan-cooled microclimates.',
    clinicalSafetyBoundary: 'Ward temperature never permitted to exceed 26.5°C; minimum air velocity maintained by BLDC fans.',
    enabled: true,
    estSavingKwHPerDay: 28.5,
  },
  {
    id: 'rule-fan-first',
    name: 'Fan-First AC Setpoint Nudge (+1.0°C)',
    category: 'HVAC',
    tagApplied: 'YELLOW',
    description: 'Leverages the ASHRAE-55 and ISHRAE thermal comfort principle: air movement from ceiling fans (0.8 m/s) feels 1.5°C cooler, allowing AC thermostat to rise from 22°C to 24.5°C.',
    clinicalSafetyBoundary: 'Clinician comfort verified; relative humidity monitored to prevent dampness.',
    enabled: true,
    estSavingKwHPerDay: 36.0,
  },
  {
    id: 'rule-opd-queue',
    name: 'OPD Queue-Linked Smart Cooling',
    category: 'OPD_INTELLIGENCE',
    tagApplied: 'YELLOW',
    description: 'Modulates OPD waiting hall AC power according to token queue density. Low cooling during 13:00-16:00 doctor lunch lulls; boost cooling 15 mins before afternoon clinic.',
    clinicalSafetyBoundary: 'OPD never allowed to exceed 27.0°C even during extreme afternoon heatwaves.',
    enabled: true,
    estSavingKwHPerDay: 22.0,
  },
  {
    id: 'rule-corridor-dimming',
    name: 'Night Corridor Dimming with NABH Safe Floor',
    category: 'LIGHTING',
    tagApplied: 'YELLOW',
    description: 'Dims corridor and passage lighting from 100% to 45% between 23:00 and 05:30. Auto-steps up to 100% if motion sensors detect stretcher or nurse transit.',
    clinicalSafetyBoundary: 'Safety floor: Lux level never drops below 80 Lux (exceeding NABH 75 Lux corridor requirement).',
    enabled: true,
    estSavingKwHPerDay: 14.5,
  },
  {
    id: 'rule-solar-shifting',
    name: 'Green-Load Solar & Off-Peak Alignment',
    category: 'SCHEDULE_SHIFT',
    tagApplied: 'GREEN',
    description: 'Shifts 5 HP water pump, linen washer, and autoclave water pre-heat to 11:00-14:30 when the 30 kWp rooftop solar array produces peak surplus.',
    clinicalSafetyBoundary: 'Zero patient contact. Water tank level low-limit sensor overrides shift if emergency reserves fall below 40%.',
    enabled: true,
    estSavingKwHPerDay: 42.0,
  },
  {
    id: 'rule-red-lockout',
    name: 'RED Zone Clinical Lockout (Hardware Interlock)',
    category: 'HVAC',
    tagApplied: 'RED',
    description: 'Operating Theatres, ICU, and Vaccine Cold Chain are physically hardwired with CT sensors only. No switching relays or contactors exist on these lines.',
    clinicalSafetyBoundary: 'ABSOLUTE LOCKOUT: Software is physically incapable of shedding, dimming, or cycling Red loads. Fail-safe guaranteed.',
    enabled: true,
    locked: true,
    estSavingKwHPerDay: 0.0,
  },
];

export const INITIAL_ALERTS: WhatsAppAlert[] = [
  {
    id: 'alert-1',
    timestamp: 'Today, 14:12',
    sender: 'Triage Gateway (+91 98201 44552)',
    title: 'AC Filter Clog Warning',
    message: '⚠️ OPD Cassette AC (CT-OPD-01): Current increased by 18% over 3 days at identical 24°C setpoint. Static pressure suggests dust fouling on indoor filter. Recommend technician wash filter to avoid compressor overheating.',
    severity: 'WARNING',
    category: 'MAINTENANCE',
    actionable: true,
    read: false,
  },
  {
    id: 'alert-2',
    timestamp: 'Today, 11:35',
    sender: 'Triage Gateway (+91 98201 44552)',
    title: 'Solar Surplus Utilized',
    message: '☀️ Rooftop Solar reached 26.2 kW. Overhead water tank pump (3.7 kW) automatically engaged. Estimated grid cost saved: ₹142.',
    severity: 'INFO',
    category: 'SAVINGS',
    actionable: false,
    read: true,
  },
  {
    id: 'alert-3',
    timestamp: 'Today, 09:10',
    sender: 'Triage Gateway (+91 98201 44552)',
    title: 'Abnormal Night Idle Power Detected',
    message: '⚡ Admin AC (CT-ADM-01) drew 2.4 kW from 21:00 to 06:00 without occupancy. Triage applied auto-sleep at 21:30. Saved 19.2 kWh (₹182.40). Please remind billing desk staff to switch off manual wall isolation.',
    severity: 'WARNING',
    category: 'SAVINGS',
    actionable: true,
    read: true,
  },
  {
    id: 'alert-4',
    timestamp: 'Today, 04:30',
    sender: 'Triage Gateway (+91 98201 44552)',
    title: 'Vaccine Cold Storage Normalcy',
    message: '🛡️ Vaccine Fridge (CT-PHARM-01): Internal temp steady at 3.9°C (safe band 2.0°C - 8.0°C). Compressor duty cycle: 38%. Red circuit status: 100% healthy.',
    severity: 'INFO',
    category: 'SAFETY',
    actionable: false,
    read: true,
  },
];

export const DEMO_STEPS = [
  {
    pageId: 'overview',
    title: 'Welcome to Triage',
    badge: '1 / 7: Clinical Philosophy',
    narration: 'Most energy management systems fail in hospitals because facilities managers fear cutting power to life support. Triage introduces clinical triage tags: RED loads are physically incapable of being shed.',
    durationMs: 12000,
  },
  {
    pageId: 'twin',
    title: 'Live Digital Twin',
    badge: '2 / 7: 50-Bed Floor Plan',
    narration: 'Inspect every zone in real-time. Notice the Operating Theatre and ICU glow RED—they are monitored only. General Wards are YELLOW (comfortable bands), while Utilities are GREEN (flexible).',
    durationMs: 14000,
  },
  {
    pageId: 'tagging',
    title: 'Clinical Lockout Protection',
    badge: '3 / 7: Patient Safety Guardrails',
    narration: 'Every load has an assigned color. If an administrator tries to drag an ICU ventilator or vaccine fridge into Yellow or Green, Triage blocks it with an instant clinical lockout warning.',
    durationMs: 14000,
  },
  {
    pageId: 'rules',
    title: 'Plain-Language Rules Engine',
    badge: '4 / 7: Clinician Approved',
    narration: 'Rules are transparent: Empty-bed standby, fan-first cooling nudges, and corridor night dimming with guaranteed NABH minimum lux floors. RED zones stay locked.',
    durationMs: 14000,
  },
  {
    pageId: 'charts',
    title: 'Energy & Money Waterfall',
    badge: '5 / 7: Clear Financial Return',
    narration: 'Comparing 24h Baseline vs Triage: green loads shift under the rooftop solar curve, reducing grid demand peaks and lowering electric bills by 22-26% without compromising patient comfort.',
    durationMs: 14000,
  },
  {
    pageId: 'safety',
    title: 'Fail-Safe Contactors & Outage Resilience',
    badge: '6 / 7: Zero Risk Guarantee',
    narration: 'Triage uses Normally-Closed bypass relays. If the kit fails or loses power, hospital loads instantly revert to grid default. During grid blackouts, Red life support stays powered first.',
    durationMs: 14000,
  },
  {
    pageId: 'roi',
    title: 'Rapid Payback Calculator',
    badge: '7 / 7: Investment Case',
    narration: 'At ₹2.85 Lakhs installed cost, a typical 50-bed nursing home pays back the entire retrofit kit in just 8 to 11 months, saving ₹3.8 Lakhs annually.',
    durationMs: 12000,
  },
];
